FROM node:18-alpine
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm ci

COPY . .

ENV NODE_ENV=production

ARG AUTH0_AUDIENCE
ARG AUTH0_DOMAIN
ARG AUTH0_CLIENT_ID
ARG AUTH0_CLIENT_SECRET

ENV VITE_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
ENV VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
ENV VITE_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
ENV VITE_AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}

RUN npm run build
RUN npm prune --omit=dev