FROM node:20-alpine
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm ci

COPY . .

ENV NODE_ENV=production

ARG __TEST
ENV TEST_VAR=${__TEST}
RUN echo ${TEST_VAR}


ARG AUTH0_AUDIENCE
RUN echo ${AUTH0_AUDIENCE}
ARG AUTH0_DOMAIN
ARG AUTH0_CLIENT_ID
ARG AUTH0_CLIENT_SECRET

ENV VITE_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
ENV VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
ENV VITE_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}

RUN echo "${VITE_AUTH0_AUDIENCE}"
RUN echo "${VITE_AUTH0_DOMAIN}"
RUN echo "${VITE_AUTH0_CLIENT_ID}"

RUN npm run build
RUN npm prune --omit=dev