### Get a clients details (200)
GET http://localhost:3000/api/v1/client/auth0|001
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVlYjIybmoyZDRJeFVpNm9JUHYwciJ9.eyJpc3MiOiJodHRwczovL3Rhc2stbWFzdGVyLmF1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NTY4ZmJlNzc2YzFiNDIxMzY3YWRjYTEiLCJhdWQiOiJodHRwczovL3Rhc2tzL2FwaSIsImlhdCI6MTcwMTM4MTcyNiwiZXhwIjoxNzAxNDY4MTI2LCJhenAiOiJhVkRBeDVBcHM4SkZpZURTTFZLVmlsTnNzZDA5UUlGdSIsImd0eSI6InBhc3N3b3JkIn0.c6pHIVXb8kbLuv0kThBgp9Xv-NVYhO3JnzREP3nZMXOfcyNx7U00eQOaPMmWZupEgZA2MPptSgf55zzK8eotOuTEWcnHPXHm7nCgsc2Om4ScAW3vzOfSjKTAfTHi0Exej7XtiYhgjHgDYXLLuTdJ9Y3KP4rcn9E-Y0_q1lCiUw2M4S46bNDM_EBOUzggOUCIyaFKBs-15WMHc1y8fKze538Pranm9TGSuWSP-tYl_qbz5NR3IpdDn0GOctoOP_CmC7EcWOORmGkTfrFjBVsKIz9RwRsBfWlXQPFOLKoj4pC3hWfDkF-7oLiVm3sjAs9ZZTIk70M84dK95mdWdOhtIA


### Try to get a client that doesn't exist (404)
GET http://localhost:3000/api/v1/client/fakeUser987
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVlYjIybmoyZDRJeFVpNm9JUHYwciJ9.eyJpc3MiOiJodHRwczovL3Rhc2stbWFzdGVyLmF1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NTY4ZmJlNzc2YzFiNDIxMzY3YWRjYTEiLCJhdWQiOiJodHRwczovL3Rhc2tzL2FwaSIsImlhdCI6MTcwMTM4MTcyNiwiZXhwIjoxNzAxNDY4MTI2LCJhenAiOiJhVkRBeDVBcHM4SkZpZURTTFZLVmlsTnNzZDA5UUlGdSIsImd0eSI6InBhc3N3b3JkIn0.c6pHIVXb8kbLuv0kThBgp9Xv-NVYhO3JnzREP3nZMXOfcyNx7U00eQOaPMmWZupEgZA2MPptSgf55zzK8eotOuTEWcnHPXHm7nCgsc2Om4ScAW3vzOfSjKTAfTHi0Exej7XtiYhgjHgDYXLLuTdJ9Y3KP4rcn9E-Y0_q1lCiUw2M4S46bNDM_EBOUzggOUCIyaFKBs-15WMHc1y8fKze538Pranm9TGSuWSP-tYl_qbz5NR3IpdDn0GOctoOP_CmC7EcWOORmGkTfrFjBVsKIz9RwRsBfWlXQPFOLKoj4pC3hWfDkF-7oLiVm3sjAs9ZZTIk70M84dK95mdWdOhtIA
