### Get a clients details (200)
GET http://localhost:3000/api/v1/client
Authorization: {{$dotenv CLIENT_TOKEN}}

### Try to get a client that doesn't exist (404)
GET http://localhost:3000/api/v1/client/fakeUser987
Authorization: {{$dotenv CLIENT_TOKEN}}

### Add a new client
POST http://localhost:3000/api/v1/client/add HTTP/1.1
Authorization: {{$dotenv CLIENT_TOKEN}}
content-type: application/json

{
  "name": "test",
  "username": "test",
  "email": "test@example.org"
}


### Get an access token (Note: must add a .env in this folder)
POST https://task-master.au.auth0.com/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

audience={{$dotenv VITE_AUTH0_AUDIENCE}}
&grant_type=password
&client_id={{$dotenv VITE_AUTH0_CLIENT_ID}}
&client_secret={{$dotenv VITE_AUTH0_CLIENT_SECRET}}
&username={{$dotenv CLIENT_USERNAME}}
&password={{$dotenv CLIENT_PASSWORD}}
